services:
  - type: web
    name: wildfire-detection-backend
    env: python
    rootDir: Project_Fire/backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn api.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
